[package]
name = "nufon-media"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
iroh = "1"
iroh-live = { git = "https://github.com/n0-computer/iroh-live", rev = "a130f15f06c3dea8a73fc87d76c729793b33ac97", default-features = false, features = ["opus", "capture"] }
nufon-protocol = { path = "../nufon-protocol" }
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread"] }
