[workspace]
resolver = "2"
members = ["crates/idfon-protocol", "crates/idfon-core", "crates/idfon-media", "crates/idfond", "crates/idfon-cli", "crates/idfon-client", "crates/idfon-daemon"]
exclude = ["native/vendor/iroh-c-ffi"]

[workspace.package]
license = "MIT OR Apache-2.0"
version = "0.4.0"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"
